version: 3

tasks:
  install:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - go mod tidy
      - task: npm-install

  generate:
    cmds:
      - wails generate module
  dev:
    cmds:
      - wails dev

  build:
    cmds:
      - wails build

  run:
    cmds:
      - wails run

  npm-install:
    internal: true
    dir: frontend
    cmds:
      - npm i