// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAndStartContainer(arg1) {
  return window['go']['app']['App']['CreateAndStartContainer'](arg1);
}

export function DeleteImage(arg1) {
  return window['go']['app']['App']['DeleteImage'](arg1);
}

export function DeleteVolume(arg1) {
  return window['go']['app']['App']['DeleteVolume'](arg1);
}

export function ExecContainer(arg1, arg2) {
  return window['go']['app']['App']['ExecContainer'](arg1, arg2);
}

export function GetContainerLogs(arg1) {
  return window['go']['app']['App']['GetContainerLogs'](arg1);
}

export function ListContainers() {
  return window['go']['app']['App']['ListContainers']();
}

export function ListContainersByCompose() {
  return window['go']['app']['App']['ListContainersByCompose']();
}

export function ListImages() {
  return window['go']['app']['App']['ListImages']();
}

export function ListVolumes() {
  return window['go']['app']['App']['ListVolumes']();
}

export function MaximiseApp() {
  return window['go']['app']['App']['MaximiseApp']();
}

export function MinimiseApp() {
  return window['go']['app']['App']['MinimiseApp']();
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function StopContainerLogs() {
  return window['go']['app']['App']['StopContainerLogs']();
}

export function StreamContainerLogs(arg1) {
  return window['go']['app']['App']['StreamContainerLogs'](arg1);
}
