// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateAndStartContainer(arg1:string):Promise<void>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeleteVolume(arg1:string):Promise<void>;

export function ExecContainer(arg1:string,arg2:string):Promise<void>;

export function GetContainerLogs(arg1:string):Promise<string>;

export function ListContainers():Promise<Array<app.ContainerInfo>>;

export function ListContainersByCompose():Promise<Array<app.ComposeProject>>;

export function ListImages():Promise<Array<app.ImageInfo>>;

export function ListVolumes():Promise<Array<app.VolumeInfo>>;

export function MaximiseApp():Promise<void>;

export function MinimiseApp():Promise<void>;

export function QuitApp():Promise<void>;

export function StopContainerLogs():Promise<void>;

export function StreamContainerLogs(arg1:string):Promise<void>;
