// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ContainerInspect(arg1:string):Promise<string>;

export function GetContainerLogs(arg1:string):Promise<string>;

export function ListContainers():Promise<Array<app.ContainerInfo>>;

export function ListImages():Promise<Array<app.ImageInfo>>;

export function MaximiseApp():Promise<void>;

export function MinimiseApp():Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveContainer(arg1:string):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopContainerLogs():Promise<void>;

export function StreamContainerLogs(arg1:string):Promise<void>;
