// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecContainer(arg1, arg2) {
  return window['go']['app']['App']['ExecContainer'](arg1, arg2);
}

export function MaximiseApp() {
  return window['go']['app']['App']['MaximiseApp']();
}

export function MinimiseApp() {
  return window['go']['app']['App']['MinimiseApp']();
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}
