// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAndStartContainer(arg1:string):Promise<void>;

export function ExecContainer(arg1:string,arg2:string):Promise<void>;

export function MaximiseApp():Promise<void>;

export function MinimiseApp():Promise<void>;

export function QuitApp():Promise<void>;
