// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartWatching(arg1) {
  return window['go']['app']['DockerLogsService']['StartWatching'](arg1);
}

export function StopWatching() {
  return window['go']['app']['DockerLogsService']['StopWatching']();
}
