// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerInspect(arg1) {
  return window['go']['app']['DockerService']['ContainerInspect'](arg1);
}

export function KillContainer(arg1) {
  return window['go']['app']['DockerService']['KillContainer'](arg1);
}

export function RemoveContainer(arg1) {
  return window['go']['app']['DockerService']['RemoveContainer'](arg1);
}

export function RestartContainer(arg1) {
  return window['go']['app']['DockerService']['RestartContainer'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['app']['DockerService']['StartContainer'](arg1);
}

export function StartWatchingContainers() {
  return window['go']['app']['DockerService']['StartWatchingContainers']();
}

export function StopContainer(arg1) {
  return window['go']['app']['DockerService']['StopContainer'](arg1);
}
