// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function List():Promise<Array<app.ImageInfo>>;

export function Remove(arg1:string):Promise<void>;

export function StartWatching():Promise<void>;

export function StopWatching():Promise<void>;
