// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List() {
  return window['go']['app']['DockerImagesService']['List']();
}

export function Remove(arg1) {
  return window['go']['app']['DockerImagesService']['Remove'](arg1);
}

export function StartWatching() {
  return window['go']['app']['DockerImagesService']['StartWatching']();
}

export function StopWatching() {
  return window['go']['app']['DockerImagesService']['StopWatching']();
}
