// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Inspect(arg1) {
  return window['go']['app']['DockerContainersService']['Inspect'](arg1);
}

export function Kill(arg1) {
  return window['go']['app']['DockerContainersService']['Kill'](arg1);
}

export function List() {
  return window['go']['app']['DockerContainersService']['List']();
}

export function Remove(arg1) {
  return window['go']['app']['DockerContainersService']['Remove'](arg1);
}

export function Restart(arg1) {
  return window['go']['app']['DockerContainersService']['Restart'](arg1);
}

export function Start(arg1) {
  return window['go']['app']['DockerContainersService']['Start'](arg1);
}

export function StartWatching() {
  return window['go']['app']['DockerContainersService']['StartWatching']();
}

export function Stop(arg1) {
  return window['go']['app']['DockerContainersService']['Stop'](arg1);
}

export function StopWatching() {
  return window['go']['app']['DockerContainersService']['StopWatching']();
}
