// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal() {
  return window['go']['app']['DockerContainersTerminal']['CloseTerminal']();
}

export function SendToTerminal(arg1) {
  return window['go']['app']['DockerContainersTerminal']['SendToTerminal'](arg1);
}

export function StartInteractiveTerminal(arg1) {
  return window['go']['app']['DockerContainersTerminal']['StartInteractiveTerminal'](arg1);
}
