// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['app']['DockerContainersTerminal']['CloseTerminal'](arg1);
}

export function SendToTerminal(arg1, arg2) {
  return window['go']['app']['DockerContainersTerminal']['SendToTerminal'](arg1, arg2);
}

export function StartInteractiveTerminal(arg1, arg2) {
  return window['go']['app']['DockerContainersTerminal']['StartInteractiveTerminal'](arg1, arg2);
}
