// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal():Promise<void>;

export function SendToTerminal(arg1:string):Promise<void>;

export function StartInteractiveTerminal(arg1:string):Promise<void>;
