// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Inspect(arg1:string):Promise<string>;

export function Kill(arg1:string):Promise<void>;

export function List():Promise<Array<app.ContainersGroup>>;

export function Remove(arg1:string):Promise<void>;

export function Restart(arg1:string):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function StartWatching():Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;
