// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Inspect(arg1) {
  return window['go']['app']['DockerVolumesService']['Inspect'](arg1);
}

export function List() {
  return window['go']['app']['DockerVolumesService']['List']();
}

export function Remove(arg1) {
  return window['go']['app']['DockerVolumesService']['Remove'](arg1);
}

export function StartWatching() {
  return window['go']['app']['DockerVolumesService']['StartWatching']();
}

export function StopWatching() {
  return window['go']['app']['DockerVolumesService']['StopWatching']();
}
