// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ContainerInspect(arg1:string):Promise<string>;

export function KillContainer(arg1:string):Promise<void>;

export function ListContainers():Promise<Array<app.ContainersGroup>>;

export function RemoveContainer(arg1:string):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartWatching():Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;
